In [7]:
import matplotlib.pyplot as plt
import cv2, re
import numpy as np
from queue import PriorityQueue

In [8]:
# BMP to JPEG conversion
img = cv2.imread('snail.bmp')

s = img.shape
new_shape = (((s[0] + 15) // 16) * 16, ((s[1] + 15) // 16) * 16, s[2])
new_image = np.zeros(new_shape, dtype = 'float32')
new_image[:s[0], :s[1], :] = img
img = np.array(new_image)
old_shape = s
s = new_shape
s1 = (s[0] // 2, s[1] // 2)

# todo - padding

# conversion from RGB format to YCbCr (Y -> Luminance, Cb -> blue chrominance, Cr -> red chrominance)
imgYCC = cv2.cvtColor(img, cv2.COLOR_BGR2YCR_CB)
Y = imgYCC[:,:,0]
Cb = np.zeros(s1, dtype = int)
Cr = np.zeros(s1, dtype = int)

# average every 2x2 block for Cb and Cr
for i in range(s[0]//2):
    for j in range(s[1]//2):
        x = i*2
        y = j*2
        avg = (imgYCC[x, y, 1] + imgYCC[x, y + 1, 1] + imgYCC[x + 1, y, 1] + imgYCC[x + 1, y + 1, 1]) // 4
        Cb[i, j] = avg
        avg = (imgYCC[x][y][2] + imgYCC[x][y + 1][2] + imgYCC[x + 1][y][2] + imgYCC[x + 1][y + 1][2]) // 4
        Cr[i, j] = avg

# Discrete Cosine Transform
Y -= 128
Cb -= 128
Cr -= 128
Y_blocks = []
Cb_blocks = []
Cr_blocks = []
for i in range(0, s[0], 8):
    for j in range(0, s[1], 8):
        grid = np.float32(Y[i:i+8, j:j+8])
        Y_blocks.append(cv2.dct(grid))
for i in range(0, s1[0], 8):
    for j in range(0, s1[1], 8):
        grid = np.float32(Cb[i:i+8, j:j+8])
        Cb_blocks.append(cv2.dct(grid))
        grid = np.float32(Cr[i:i+8, j:j+8])
        Cr_blocks.append(cv2.dct(grid))

len_y = len(Y_blocks)
len_c = len(Cb_blocks)

# Quantization
Y_q = np.array([[4., 3, 4, 4, 4, 6, 11, 15], [3, 3, 3, 4, 5, 8, 14, 19], [3, 4, 4, 5, 8, 12, 16, 20], [4, 5, 6, 7, 12, 14, 18, 20], [6, 6, 9, 11, 14, 17, 21, 23], [9, 12, 12, 18, 23, 22, 25, 21], [11, 13, 15, 17, 21, 23, 25, 21], [13, 12, 12, 13, 16, 19, 21, 21]])
C_q = np.array([[4., 4, 6, 10, 21, 21, 21, 21], [4, 5, 6, 21, 21, 21, 21, 21], [6, 6, 12, 21, 21, 21, 21, 21], [10, 14, 21, 21, 21, 21, 21, 21], [21, 21, 21, 21, 21, 21, 21, 21], [21, 21, 21, 21, 21, 21, 21, 21], [21, 21, 21, 21, 21, 21, 21, 21], [21, 21, 21, 21, 21, 21, 21, 21]])
for i in range(len_y):
    Y_blocks[i] //= Y_q
for i in range(len_c):
    Cb_blocks[i] //= C_q
for i in range(len_c):
    Cr_blocks[i] //= C_q

# Run length encoding
def spiral_traversal(block):
    p = 8
    arr = np.array([])
    k = 0
    for c in range(p):
        for i in range(0, k+1):
            if k%2!=0 :
                arr = np.append(arr, block[i][k-i])
            else :
                arr = np.append(arr, block[k-i][i])
        k+=1

    k = 1
    for c in range(p-1):
        j = p
        for i in range(k, p):
            j-=1
            if k%2 == 0:
                arr = np.append(arr, block[i][j])
            else:
                arr = np.append(arr, block[j][i])
        k+=1
    return arr

dc = 0
def encode(block):
    global dc
    temp = spiral_traversal(block)
    l = len(temp)

    encoded_block = []
    encoded_block.append((0, temp[0] - dc))
    dc = temp[0]
    c0 = 0
    for i in range(1, l):
        if temp[i] or c0==15 :
            encoded_block.append((c0, temp[i]))
            c0 = 0
        else:
            c0 += 1
    encoded_block.append((0, 0))

    encoded_block = np.array(encoded_block, dtype = int)
    return encoded_block

encoded_Y = list()
encoded_Cr = list()
encoded_Cb = list()
for i in range(len_y):
    encoded_Y.append(encode(Y_blocks[i]))
for i in range(len_c):
    encoded_Cb.append(encode(Cb_blocks[i]))
    encoded_Cr.append(encode(Cr_blocks[i]))
encoded_Y = np.array(encoded_Y, dtype = object)
encoded_Cr = np.array(encoded_Cr, dtype = object)
encoded_Cb = np.array(encoded_Cb, dtype = object)

# print(encoded_Y, encoded_Cb, encoded_Cr, sep = '\n')

# Huffman Tables
def get_cat(num): ##extracting position of msb to determine what length of bits it will need to be encoded
    num = int(abs(num))
    ans = 0
    pwr = 1
    while pwr < num:
        pwr <<= 1
        ans += 1
    return ans
##***********************************************************DANGER**********************


def make_freq_table(dc_freq, ac_freq, encoded_blocks):
    for block in encoded_blocks:
        #block of length 64 usually (we take 8*8 grids), first element is dc coeff, the rest are ac coeffs
        #dc block[0] is encoded as (0, value)
        dc = block[0]
        dc_run_length, dc_val = dc #dc_run_length will be 0
        
        cat = get_cat(dc_val)
        dc_freq[dc_run_length, cat] += 1
        
        for i in range(1, len(block)):
            
            #ac block[i] is encoded as (run length of zeros before value max 15, value of ith non zero ac coefficient)
            ac_i = block[i]
            run_length, value = ac_i
            cat = get_cat(value) # find the category of value
            ac_freq[run_length, cat] += 1
            
dc_huffman_Y = np.zeros((1, 16), dtype=int)
ac_huffman_Y = np.zeros((16,16), dtype=int)
dc_huffman_C = np.zeros((1, 16), dtype=int)
ac_huffman_C = np.zeros((16,16), dtype=int)

make_freq_table(dc_huffman_Y, ac_huffman_Y, encoded_Y)
make_freq_table(dc_huffman_C, ac_huffman_C, encoded_Cr)
make_freq_table(dc_huffman_C, ac_huffman_C, encoded_Cb)



# make huffman codes
depth = 0
def get_codebook(freq):
    codebook = np.empty(freq.shape, dtype = object)
    def get_code_lengths(freq):

        def make_tree(freq):
            global code
            q = PriorityQueue()
            m = len(freq)
            n = len(freq[0])

            cnt = 0
            for i in range(m):
                for j in range(n):
                    if freq[i,j]:
                        q.put((freq[i,j], str((i,j))))
                        cnt += 1

            for i in range(cnt-1):
                a = q.get()
                b = q.get()
                q.put((a[0]+b[0], str("[" + a[1] + "," + b[1] + "]")))

            tree = eval(q.get()[1])
            return tree

        tree = make_tree(freq)
        code_lengths = np.zeros(freq.shape, dtype=int)

        def get_depths(arr, code_lengths):
            global depth
            if type(arr[1]) == int and type(arr[0]) == int:
                code_lengths[arr[0], arr[1]] = min(depth, 16)
            else:
                depth += 1
                get_depths(arr[0], code_lengths)
                get_depths(arr[1], code_lengths)
                depth-=1

        get_depths(tree, code_lengths)
        return code_lengths
    
    code_lengths = get_code_lengths(freq)
    length_symbol_pairs = []
    
    m, n = freq.shape
    for i in range(m):
        for j in range(n):
            if code_lengths[i, j]:
                length_symbol_pairs.append((code_lengths[i, j], (i, j)))
    length_symbol_pairs.sort()
    
    def get_code(code, length):
        st = bin(code).replace("0b", "")[::-1]
        while len(st) < length:
            st += '0'
        return st[::-1]
    
    code = 0
    cur_len = 0
    for length, symbol in length_symbol_pairs:
        while cur_len < length:  #if there is no symbol with the current length
            cur_len += 1
            code *= 2
        codebook[symbol[0], symbol[1]] = get_code(code, length)
        code += 1
    
    return codebook, length_symbol_pairs

codes_dc_Y, sorted_symbols_dc_Y = get_codebook(dc_huffman_Y)
codes_ac_Y, sorted_symbols_ac_Y = get_codebook(ac_huffman_Y)
codes_dc_C, sorted_symbols_dc_C = get_codebook(dc_huffman_C)
codes_ac_C, sorted_symbols_ac_C = get_codebook(ac_huffman_C)

def to_two_bytes(num):
    bh = bin(num).replace("0b", "")
    bh = bh[::-1]
    while len(bh) < 16:
        bh += '0'
    bh = bh[::-1]

    return [int(bh[:8], 2), int(bh[8:], 2)]

# Writing jpeg image in binary
jpeg_image = [0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10]

header = [0x4a, 0x46, 0x49, 0x46, 0x00, 0x01, 0x01, 0x01, 0x00, 0x48, 0x00, 0x48, 0x00, 0x00]
jpeg_image.extend(header)

luminance_quantisation_table = [0xff, 0xdb, 0x00, 0x43, 0x00]
for ele in Y_q:
    for x in ele:
        luminance_quantisation_table.append(int(x))
jpeg_image.extend(luminance_quantisation_table)

chrominance_quantisation_table = [0xff, 0xdb, 0x00, 0x43, 0x01]
for ele in C_q:
    for x in ele:
        chrominance_quantisation_table.append(int(x))
jpeg_image.extend(chrominance_quantisation_table)

start_of_frame = [0xff, 0xc0, 0x00, 0x11, 0x08]
start_of_frame.extend(to_two_bytes(old_shape[0]))
start_of_frame.extend(to_two_bytes(old_shape[1]))
start_of_frame.extend([0x03, 0x01, 0x22, 0x00, 0x02, 0x11, 0x01, 0x03, 0x11, 0x01])
jpeg_image.extend(start_of_frame)

def parse_table(sorted_symbols, typ):
    table = [0xff, 0xc4]
    ln = 19
    symbols = []
    freqs = [0 for i in range(16)]
    
    for length, symbol in sorted_symbols:
        freqs[length - 1] += 1
        symbols.append(symbol[0] * 16 + symbol[1])
        ln += 1
    
    table.extend(to_two_bytes(ln))
    table.append(typ)
    table.extend(freqs)
    table.extend(symbols)
    return table

jpeg_image.extend(parse_table(sorted_symbols_dc_Y, 0x00))
jpeg_image.extend(parse_table(sorted_symbols_ac_Y, 0x10))
jpeg_image.extend(parse_table(sorted_symbols_dc_C, 0x01))
jpeg_image.extend(parse_table(sorted_symbols_ac_C, 0x11))

start_of_scan = [0xff, 0xda, 0x00, 0x0c, 0x03, 0x01, 0x00, 0x02, 0x11, 0x03, 0x11, 0x00, 0x3f, 0x00]
jpeg_image.extend(start_of_scan)

def bit_rep(value):
    if value == 0:
        return ''
    else : 
        v = bin(abs(value)).replace("0b", '')
        if value>0 :
            return v
        else:
            return v.replace('0', 'a').replace('1','0').replace('a','1')

def encode_data(data_blocks, dc_codebook, ac_codebook):
    s = ''
    for block in data_blocks:
        dc_val = block[0][1]
        cat = get_cat(dc_val)
        s+=(dc_codebook[0,cat]+bit_rep(dc_val))
        
        for i in range(1, len(block)):
            run, val = block[i]
            s+=(ac_codebook[run, get_cat(val)]+bit_rep(val))
    #pad with 0s
    a = len(s)%8
    s+='0'*a
    
    data = [int(s[i:i+8], 2) for i in range(0, len(s), 8)]
    return data
    
        
jpeg_image.extend(encode_data(encoded_Y, codes_dc_Y, codes_ac_Y))
jpeg_image.extend(encode_data(encoded_Cb, codes_dc_C, codes_ac_C))
jpeg_image.extend(encode_data(encoded_Cr, codes_dc_C, codes_ac_C))

end_of_image = [0xff, 0xd9]
jpeg_image.extend(end_of_image)

try:
    with open("my_image.jpeg", 'wb') as f:
        for byte in jpeg_image:
            f.write(byte.to_bytes(1, byteorder='big'))
except Exception as e:
    print(e)

file = open('my_image.jpeg', 'rb')
data = file.read()
s = data.hex()

l = re.findall('..?', s)
d = np.reshape(l, (-1, 4))
d = [' '.join(ele) for ele in d]
# for ele in d:
#     print(ele)
file.close()

In [9]:
# encoded_Y
# (int)(np.log2(abs(-21))+1)

# dc_huffman = np.random.randint(160, size=16)
dc_huffman = [ 25,2, 90,  11, 108 , 36,  23, 107, 145,   0,  40,  76,  71, 146, 151,  21]
print(dc_huffman)
q = PriorityQueue()

for i in range(16):
    q.put((dc_huffman[i], (i,)))

for i in range(15):
    a = q.get()
    b = q.get()
    q.put((a[0]+b[0], (a[1], b[1])))
    
f = q.get()
print(f)

codes_dc_Y = ['' for i in range(16)]
code = ""
def create_codes(arr):
    global code
    if len(arr) == 1:
        codes_dc_Y[arr[0]] = code
    else:
        code += "0"
        create_codes(arr[0])
        code = code[:-1]
        code += "1"
        create_codes(arr[1])
        code = code[:-1]
create_codes(f[1])
print(codes_dc_Y)

[25, 2, 90, 11, 108, 36, 23, 107, 145, 0, 40, 76, 71, 146, 151, 21]
(1052, ((((2,), (7,)), ((4,), ((((((9,), (1,)), (3,)), (15,)), (5,)), (12,)))), (((8,), (13,)), ((14,), ((11,), ((10,), ((6,), (0,))))))))
['111111', '01100001', '000', '0110001', '010', '01101', '111110', '001', '100', '01100000', '11110', '1110', '0111', '101', '110', '011001']


In [4]:

dc_huffman_Y = np.array([ 25,2, 90,  11, 108 , 36,  23, 107, 145,   0,  40,  76,  71, 146, 151,  21]).reshape((16, 1))
ac_huffman_Y = np.array([[ 57,  16,  42, 157,  71,  67, 153,  90,   6,  51,  51,  38, 137,
         77, 156,  62],
       [ 94, 158, 116,  40,  21, 112, 109,  10,  69, 104, 115,  38,  56,
         17,  98, 136],
       [ 26,  68, 107, 131, 121, 132,  12, 100,  27,  91,  58,  14, 142,
         66,  11, 102],
       [ 88, 118,  58, 147, 110, 118, 125,  22,  13,  24,  96, 113,  16,
        111, 122, 110],
       [158, 118,  14,  84, 103, 155, 116,  43,  49, 133,  13,  13,  13,
          4, 148,   4],
       [  9, 145,  55,  43,  20,  24,  89,  44,  42,  93, 132,  60,  94,
         89,  61,  87],
       [ 19, 132, 125, 113,  29,  49,  67,  32, 104, 138,  83,  97, 130,
         36,  77,  15],
       [ 92, 108,  21,  81,  67, 138, 113,   9, 144,  46,  50,  87,  65,
        111, 127,  35],
       [152,  86,  59, 159,  32,  50,   4, 111, 150, 137,  51,   4,  80,
         50,   7, 158],
       [ 65,  47,  55,  61, 125, 130,  27, 106,  46,  17,  76, 109,  47,
         49, 146,  79],
       [  6, 157,  85,  51,  22, 128,  33,  59,  54,  61,  65,  82,  75,
         17,  87, 112],
       [142, 153,  46,  17,   1, 152,  58,  39,  52, 105, 111, 138,  61,
         85, 148,  15],
       [117, 128, 116,  67, 141, 132,  64,  65,  99,  48, 154,  86,  70,
         80,  82,  52],
       [ 92,  49,  17,  12,  22,  98,  31,  84,  52,   0,  59,  17,  52,
         69,  89, 113],
       [134,  65,  90,  46,  31, 122,  35, 154, 123,  12, 133,  39, 119,
         44,  60,  45],
       [ 16,  81, 149,  42,  17,  54, 146,  49,  76,   6,  37, 152,  83,
         27, 123,  17]]).reshape((16,16))
#[[4599 1687 1701 1464 1007  598  379  187   58    0    0    0    0    0
#      0    0]
#  [ 786  248  199   96   42    9    7    2    1    0    0    0    0    0
#      0    0]
#  [ 326   63   36   13    2    2    2    0    0    0    0    0    0    0
#      0    0]
#  [ 116   12    9    2    1    1    0    0    0    0    0    0    0    0
#      0    0]
#  [  60    6    3    0    0    0    0    0    0    0    0    0    0    0
#      0    0]
#  [  20    1    1    0    0    0    0    0    0    0    0    0    0    0
#      0    0]
#  [  12    1    0    0    0    0    0    0    0    0    0    0    0    0
#      0    0]
#  [   8    2    0    0    0    0    0    0    0    0    0    0    0    0
#      0    0]
#  [   3    0    0    0    0    0    0    0    0    0    0    0    0    0
#      0    0]
#  [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
#      0    0]
#  [   1    0    0    0    0    0    0    0    0    0    0    0    0    0
#      0    0]
#  [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
#      0    0]
#  [   1    0    0    0    0    0    0    0    0    0    0    0    0    0
#      0    0]
#  [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
#      0    0]
#  [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
#      0    0]
#  [2301    0    0    0    0    0    0    0    0    0    0    0    0    0
#      0    0]]
code = ""
def get_codebook(freq):
    q = PriorityQueue()
    m = len(freq)
    n = len(freq[0])
    codebook = np.empty((m, n), dtype = object)

    cnt = 0
    for i in range(m):
        for j in range(n):
            if freq[i,j]:
                q.put((freq[i,j], str((i,j))))
                cnt += 1

    for i in range(cnt - 1):
        a = q.get()
        b = q.get()
        q.put((a[0]+b[0], str((eval(a[1]), eval(b[1])))))

    tree = eval(q.get()[1])
    print(tree)
    
    def create_codes(arr, codebook):
        global code
        if type(arr[1]) == int and type(arr[0]) == int:
            codebook[arr[0], arr[1]] = code
        else:
            code += "0"
            create_codes(arr[0], codebook)
            code = code[:-1]
            code += "1"
            create_codes(arr[1], codebook)
            code = code[:-1]
            
    create_codes(tree, codebook)
    return codebook

codes_dc_Y = get_codebook(dc_huffman_Y)
print(codes_dc_Y)

codes_ac_Y = get_codebook(ac_huffman_Y)
print(codes_ac_Y)

((((2, 0), (7, 0)), ((4, 0), (((((1, 0), (3, 0)), (15, 0)), (5, 0)), (12, 0)))), (((8, 0), (13, 0)), ((14, 0), ((11, 0), ((10, 0), ((6, 0), (0, 0)))))))
[['111111']
 ['0110000']
 ['000']
 ['0110001']
 ['010']
 ['01101']
 ['111110']
 ['001']
 ['100']
 [None]
 ['11110']
 ['1110']
 ['0111']
 ['101']
 ['110']
 ['011001']]
((((((((3, 11), (6, 3)), ((7, 6), ((0, 0), (11, 6)))), (((1, 10), ((2, 10), (3, 2))), ((1, 2), (12, 2)))), ((((4, 6), (12, 0)), (((10, 7), (13, 10)), (3, 1))), (((3, 5), (4, 1)), (((8, 2), ((6, 4), ((6, 15), (0, 1)))), (14, 12))))), ((((((14, 14), (5, 11)), (2, 4)), (((10, 9), (11, 12)), ((5, 14), (9, 3)))), (((14, 5), (3, 14)), ((14, 8), (15, 14)))), ((((((13, 6), (14, 4)), (0, 15)), (3, 6)), ((6, 2), (9, 4))), (((7, 14), ((((15, 0), (3, 12)), (6, 7)), (12, 6))), ((10, 5), (12, 1)))))), ((((((((8, 4), (10, 6)), (10, 10)), ((12, 7), (14, 1))), (((7, 12), (9, 0)), (6, 12))), (((9, 5), (2, 3)), ((12, 5), (2, 5)))), ((((5, 10), (6, 1)), (((2, 13), (0, 5)), (14, 10))), (((4, 

In [34]:
# np.random.randint(160,size=(16,16))
# for ele in encoded_Y:
#     cat = get_msb_pos(ele[0][1])
#     dc_huffman_Y[0, cat] += 1

#     for i in range(1, len(ele)):
#         # find the category
#         cat = get_msb_pos(ele[i][1])
#         ac_huffman_Y[ele[i][0], cat] += 1

# for ele in encoded_Cr:
#     cat = get_msb_pos(ele[0][1])
#     dc_huffman_C[0, cat] += 1                           

#     for i in range(1, len(ele)):
#         # find the category
#         cat = get_msb_pos(ele[i][1])
#         ac_huffman_C[ele[i][0], cat] += 1

# for ele in encoded_Cb:
#     cat = get_msb_pos(ele[0][0])
#     dc_huffman_C[0, cat] += 1                           

#     for i in range(1, len(ele)):
#         # find the category
#         cat = get_msb_pos(ele[i][1])
#         ac_huffman_C[ele[i][0], cat] += 1

In [32]:
# def spiral_traversal(block):
#     p = 8
#     arr = np.array([])
#     k = 0
#     for c in range(p):
#         for i in range(0, k+1):
#             if k%2!=0 :
#                 arr = np.append(arr, block[i][k-i])
#             else :
#                 arr = np.append(arr, block[k-i][i])
#         k+=1
        
#     k = 1
#     for c in range(p-1):
#         j = p
#         for i in range(k, p):
#             j-=1
#             if k%2 == 0:
#                 arr = np.append(arr, block[i][j])
#             else:
#                 arr = np.append(arr, block[j][i])
#         k+=1
#     return arr
        
# Y_q = np.array([[4., 3, 4, 4, 4, 6, 11, 15], [3, 3, 3, 4, 5, 8, 14, 19], [3, 4, 4, 5, 8, 12, 16, 20], [4, 5, 6, 7, 12, 14, 18, 20], [6, 6, 9, 11, 14, 17, 21, 23], [9, 12, 12, 18, 23, 22, 25, 21], [11, 13, 15, 17, 21, 23, 25, 21], [13, 12, 12, 13, 16, 19, 21, 21]])
# print(Y_q)
# print(spiral_traversal(Y_q))

In [33]:
# arr = np.zeros([])
# arr = np.append(arr,1)
# arr

In [30]:
# img = np.asarray(cv2.imread('waterpool.bmp', 0))
# print(list(img[0]))

In [31]:
# img = cv2.imread('waterpool.jpeg')
# print(img)

In [13]:
file = open('snail.jpeg', 'rb')
data = file.read()
s = data.hex()

import re
l = re.findall('..?', s)
print(len(l))
d = np.reshape(l, (-1, 11))
d = [' '.join(ele) for ele in d]
# for ele in d:
#     print(ele)
file.close()

print(data.binary())

bit_rep(-63)

13211


AttributeError: 'bytes' object has no attribute 'binary'

In [ ]:
# make huffman codes
code = ""
def get_codebook(freq):
    global code
    q = PriorityQueue()
    m = len(freq)
    n = len(freq[0])
    codebook = np.empty((m, n), dtype = object)

    cnt = 0
    for i in range(m):
        for j in range(n):
            if freq[i,j]:
                q.put((freq[i,j], str((i,j))))
                cnt += 1

    for i in range(cnt-1):
        a = q.get()
        b = q.get()
        q.put((a[0]+b[0], str("[" + a[1] + "," + b[1] + "]")))

    tree = eval(q.get()[1])

    code = ""
    def create_codes(arr, codebook):
        global code
        if type(arr[1]) == int and type(arr[0]) == int:
            codebook[arr[0], arr[1]] = code
        else:
            code += "0"
            create_codes(arr[0], codebook)
            code = code[:-1]
            code += "1"
            create_codes(arr[1], codebook)
            code = code[:-1]

    create_codes(tree, codebook)
    return codebook

codes_dc_Y = get_codebook(dc_huffman_Y)
codes_ac_Y = get_codebook(ac_huffman_Y)
codes_dc_C = get_codebook(dc_huffman_C)
codes_ac_C = get_codebook(ac_huffman_C)

In [47]:
import numpy as np
from PIL import Image

image = cv2.imread('snail.bmp')
s = image.shape
new_shape = (((s[0] + 15) // 16) * 16, ((s[1] + 15) // 16) * 16, s[2])
new_image = np.zeros(new_shape, dtype = 'float32')
new_image[:s[0],:s[1],:] = image
old_shape = s
s = new_shape
s1 = (s[0] // 2, s[1] // 2)

R = new_image[:,:,2]
G = new_image[:,:,1]
B = new_image[:,:,0]
# print(R)
Y = 0.299*R + 0.587*G + 0.114*B
cbb = 128 - 0.168736*R - 0.331264*G + 0.5*B
crr = 128 + 0.5*R - 0.418688*G - 0.081312*B
Cb = np.zeros(s1, dtype = float)
Cr = np.zeros(s1, dtype = float)

# average every 2x2 block for Cb and Cr
for i in range(s[0]//2):
    for j in range(s[1]//2):
        x = i*2
        y = j*2
        avg = (cbb[x, y] + cbb[x, y + 1] + cbb[x + 1, y] + cbb[x + 1, y + 1]) // 4
        Cb[i, j] = avg
        avg = (crr[x, y] + crr[x, y + 1] + crr[x + 1, y] + crr[x + 1, y + 1]) // 4
        Cr[i, j] = avg

# Discrete Cosine Transform
Y -= 128
Cb -= 128
Cr -= 128
Y_blocks = []
Cb_blocks = []
Cr_blocks = []
for i in range(0, s1[0], 8):
    for j in range(0, s1[1], 8):
        grid = np.float32(Cb[i:i+8, j:j+8])
        Cb_blocks.append(cv2.dct(grid))
        if i==0 and j==0: 
            pass
#             print(grid)
#             print(Cb_blocks[0])
        grid = np.float32(Cr[i:i+8, j:j+8])
        Cr_blocks.append(cv2.dct(grid))
        grid = np.float32(Y[i*2:i*2+8, j*2:j*2+8])
        Y_blocks.append(cv2.dct(grid))
        if i==0 and j==0: 
            pass
#             print(grid)
#             print(Y_blocks[0])
        grid = np.float32(Y[i*2:i*2+8, j*2+8:j*2+16])
        Y_blocks.append(cv2.dct(grid))
        grid = np.float32(Y[i*2+8:i*2+16, j*2:j*2+8])
        Y_blocks.append(cv2.dct(grid))
        grid = np.float32(Y[i*2+8:i*2+16, j*2+8:j*2+16])
        Y_blocks.append(cv2.dct(grid))

len_y = len(Y_blocks)
len_c = len(Cb_blocks)

# Quantization

def spiralo(block):
    p = 8
    arr = []
    k = 0
    for c in range(p):
        for i in range(0, k+1):
            if k%2!=0 :
                arr.append(block[i][k-i])
            else :
                arr.append(block[k-i][i])
        k+=1

    k = 1
    for c in range(p-1):
        j = p
        for i in range(k, p):
            j-=1
            if k%2 == 0:
                arr.append(block[i][j])
            else:
                arr.append(block[j][i])
        k+=1
    return arr

# Quantization
myArr = [
[0x03, 0x02, 0x02, 0x03, 0x02, 0x02, 0x03, 0x03],
[0x03, 0x03, 0x04, 0x03, 0x03, 0x04, 0x05, 0x08],
[0x05, 0x05, 0x04, 0x04, 0x05, 0x0a, 0x07, 0x07],
[0x06, 0x08, 0x0c, 0x0a, 0x0c, 0x0c, 0x0b, 0x0a],
[0x0b, 0x0b, 0x0d, 0x0e, 0x12, 0x10, 0x0d, 0x0e],
[0x11, 0x0e, 0x0b, 0x0b, 0x10, 0x16, 0x10, 0x11],
[0x13, 0x14, 0x15, 0x15, 0x15, 0x0c, 0x0f, 0x17],
[0x18, 0x16, 0x14, 0x18, 0x12, 0x14, 0x15, 0x14]
]
myArr2 = [
[0x03, 0x04, 0x04, 0x05, 0x04, 0x05, 0x09, 0x05],
[0x05, 0x09, 0x14, 0x0d, 0x0b, 0x0d, 0x14, 0x14],
[0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14],
[0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14],
[0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14],
[0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14],
[0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14],
[0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14]
]
spiral = [[(i, j) for j in range(8)] for i in range(8)]
spiral = spiralo(spiral)
Y_q = np.array([[4., 3, 4, 4, 4, 6, 11, 15], [3, 3, 3, 4, 5, 8, 14, 19], [3, 4, 4, 5, 8, 12, 16, 20], [4, 5, 6, 7, 12, 14, 18, 20], [6, 6, 9, 11, 14, 17, 21, 23], [9, 12, 12, 18, 23, 22, 25, 21], [11, 13, 15, 17, 21, 23, 25, 21], [13, 12, 12, 13, 16, 19, 21, 21]])
C_q = np.array([[4., 4, 6, 10, 21, 21, 21, 21], [4, 5, 6, 21, 21, 21, 21, 21], [6, 6, 12, 21, 21, 21, 21, 21], [10, 14, 21, 21, 21, 21, 21, 21], [21, 21, 21, 21, 21, 21, 21, 21], [21, 21, 21, 21, 21, 21, 21, 21], [21, 21, 21, 21, 21, 21, 21, 21], [21, 21, 21, 21, 21, 21, 21, 21]])
cur = 0
for i in range(8):
    for j in range(8):
        Y_q[spiral[cur][0]][spiral[cur][1]] = myArr[i][j]
        C_q[spiral[cur][0]][spiral[cur][1]] = myArr2[i][j]
        cur += 1
        
bound = 32767
for i in range(len_y):
    Y_blocks[i] = np.around(Y_blocks[i] / Y_q)
    for j in range(len(Y_blocks[i])):
        for k in range(len(Y_blocks[i][j])):
            if abs(Y_blocks[i][j][k]) > bound:
                if Y_blocks[i][j][k] > 0:
                    Y_blocks[i][j][k] = bound
                else:
                    Y_blocks[i][j][k] = -bound
for i in range(len_c):
    Cb_blocks[i] = np.around(Cb_blocks[i] / C_q)
    for j in range(len(Cb_blocks[i])):
        for k in range(len(Cb_blocks[i][j])):
            if abs(Cb_blocks[i][j][k]) > bound:
                if Cb_blocks[i][j][k] > 0:
                    Cb_blocks[i][j][k] = bound
                else:
                    Cb_blocks[i][j][k] = -bound
for i in range(len_c):
    Cr_blocks[i] = np.around(Cr_blocks[i] / C_q)
    for j in range(len(Y_blocks[i])):
        for k in range(len(Y_blocks[i][j])):
            if abs(Cr_blocks[i][j][k]) > bound:
                if Cr_blocks[i][j][k] > 0:
                    Cr_blocks[i][j][k] = bound
                else:
                    Cr_blocks[i][j][k] = -bound

# Run length encoding
def spiral_traversal(block):
    p = 8
    arr = np.array([])
    k = 0
    for c in range(p):
        for i in range(0, k+1):
            if k%2!=0 :
                arr = np.append(arr, block[i][k-i])
            else :
                arr = np.append(arr, block[k-i][i])
        k+=1

    k = 1
    for c in range(p-1):
        j = p
        for i in range(k, p):
            j-=1
            if k%2 == 0:
                arr = np.append(arr, block[i][j])
            else:
                arr = np.append(arr, block[j][i])
        k+=1
    return arr

dc = 0
def encode(block):
    global dc
    temp = spiral_traversal(block)
    l = len(temp)

    encoded_block = []
    encoded_block.append((0, temp[0] - dc))
    dc = temp[0]
    c0 = 0
    cnz = 0
    for i in range(1, l):
        if temp[i]: cnz += 1
    for i in range(1, l):
        if cnz == 0:
            break
        if temp[i] or c0==15 :
            encoded_block.append((c0, temp[i]))
            c0 = 0
            if temp[i]:
                cnz -= 1
        else:
            c0 += 1
    encoded_block.append((0, 0))
    
    encoded_block = np.array(encoded_block, dtype = int)
    return encoded_block

encoded_Y = list()
encoded_Cr = list()
encoded_Cb = list()
for i in range(len_y):
    encoded_Y.append(encode(Y_blocks[i]))
dc = 0
for i in range(len_c):
    encoded_Cb.append(encode(Cb_blocks[i]))
dc = 0
for i in range(len_c):
    encoded_Cr.append(encode(Cr_blocks[i]))
encoded_Y = np.array(encoded_Y, dtype = object)
encoded_Cr = np.array(encoded_Cr, dtype = object)
encoded_Cb = np.array(encoded_Cb, dtype = object)

# print(encoded_Y[:4], encoded_Cb[0], encoded_Cr[0], sep = '\n')

# print(encoded_Y, encoded_Cb, encoded_Cr, sep = '\n')

# Huffman Tables
def get_cat(num): ##extracting position of msb to determine what length of bits it will need to be encoded
    num = int(abs(num))
    ans = 0
    pwr = 1
    while pwr <= num:
        pwr <<= 1
        ans += 1
    return ans
##***********************************************************DANGER**********************


def make_freq_table(dc_freq, ac_freq, encoded_blocks):
    for block in encoded_blocks:
        #block of length 64 usually (we take 8*8 grids), first element is dc coeff, the rest are ac coeffs
        #dc block[0] is encoded as (0, value)
        dc = block[0]
        dc_run_length, dc_val = dc #dc_run_length will be 0
        
        cat = get_cat(dc_val)
        dc_freq[dc_run_length, cat] += 1
        
        for i in range(1, len(block)):
            
            #ac block[i] is encoded as (run length of zeros before value max 15, value of ith non zero ac coefficient)
            ac_i = block[i]
            run_length, value = ac_i
            cat = get_cat(value) # find the category of value
            ac_freq[run_length, cat] += 1
            
dc_huffman_Y = np.zeros((1, 16), dtype=int)
ac_huffman_Y = np.zeros((16,16), dtype=int)
dc_huffman_C = np.zeros((1, 16), dtype=int)
ac_huffman_C = np.zeros((16,16), dtype=int)

make_freq_table(dc_huffman_Y, ac_huffman_Y, encoded_Y)
make_freq_table(dc_huffman_C, ac_huffman_C, encoded_Cr)
make_freq_table(dc_huffman_C, ac_huffman_C, encoded_Cb)



# make huffman codes
depth = 0
hufs = [[0x00, 0x01, 0x05, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b], 
        [0x00, 0x02, 0x01, 0x03, 0x03, 0x02, 0x04, 0x03, 0x05, 0x05, 0x04, 0x04, 0x00, 0x00, 0x01, 0x7d, 0x01, 0x02, 0x03, 0x00, 0x04, 0x11, 0x05, 0x12, 0x21, 0x31, 0x41, 0x06, 0x13, 0x51, 0x61, 0x07, 0x22, 0x71, 0x14, 0x32, 0x81, 0x91, 0xa1, 0x08, 0x23, 0x42, 0xb1, 0xc1, 0x15, 0x52, 0xd1, 0xf0, 0x24, 0x33, 0x62, 0x72, 0x82, 0x09, 0x0a, 0x16, 0x17, 0x18, 0x19, 0x1a
, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2a, 0x34, 0x35, 0x36, 0x37, 0x38
, 0x39, 0x3a, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x53
, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5a, 0x63, 0x64, 0x65, 0x66
, 0x67, 0x68, 0x69, 0x6a, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79
, 0x7a, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x92, 0x93
, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0xa2, 0xa3, 0xa4, 0xa5
, 0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xb2, 0xb3, 0xb4, 0xb5, 0xb6, 0xb7
, 0xb8, 0xb9, 0xba, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9
, 0xca, 0xd2, 0xd3, 0xd4, 0xd5, 0xd6, 0xd7, 0xd8, 0xd9, 0xda, 0xe1
, 0xe2, 0xe3, 0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xf1, 0xf2
, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9, 0xfa],
       [0x00, 0x03, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01
, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x02, 0x03
, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b],
       [0x00, 0x02, 0x01, 0x02, 0x04, 0x04, 0x03, 0x04, 0x07
, 0x05, 0x04, 0x04, 0x00, 0x01, 0x02, 0x77, 0x00, 0x01, 0x02, 0x03
, 0x11, 0x04, 0x05, 0x21, 0x31, 0x06, 0x12, 0x41, 0x51, 0x07, 0x61
, 0x71, 0x13, 0x22, 0x32, 0x81, 0x08, 0x14, 0x42, 0x91, 0xa1, 0xb1
, 0xc1, 0x09, 0x23, 0x33, 0x52, 0xf0, 0x15, 0x62, 0x72, 0xd1, 0x0a
, 0x16, 0x24, 0x34, 0xe1, 0x25, 0xf1, 0x17, 0x18, 0x19, 0x1a, 0x26
, 0x27, 0x28, 0x29, 0x2a, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x43
, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x53, 0x54, 0x55, 0x56
, 0x57, 0x58, 0x59, 0x5a, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69
, 0x6a, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7a, 0x82, 0x83
, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x92, 0x93, 0x94, 0x95
, 0x96, 0x97, 0x98, 0x99, 0x9a, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7
, 0xa8, 0xa9, 0xaa, 0xb2, 0xb3, 0xb4, 0xb5, 0xb6, 0xb7, 0xb8, 0xb9
, 0xba, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9, 0xca, 0xd2
, 0xd3, 0xd4, 0xd5, 0xd6, 0xd7, 0xd8, 0xd9, 0xda, 0xe2, 0xe3, 0xe4
, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6
, 0xf7, 0xf8, 0xf9, 0xfa]]



def get_codebook(freq, index):
    codebook = np.empty(freq.shape, dtype = object)
    def get_code_lengths_from_huf(huf_table, m, n):
        #for dc m = 1, n = 16
        code_lengths = np.zeros((m,n), dtype=int)
        counts = np.zeros(17, dtype=int)
        for length in range(1, 17):
            counts[length] = huf_table[length-1]
        l = len(huf_table)
        ctr = 0
        for w in range(16, l):
            symbol = huf_table[w]
            i = symbol//16
            j = symbol%16
            while counts[ctr]==0: ctr+=1
#             print(ctr, i, j)
            code_lengths[i, j] = ctr
            counts[ctr]-=1
#         print(code_lengths)
        return code_lengths
    
    def get_code_lengths(freq):

        def make_tree(freq):
            global code
            q = PriorityQueue()
            m = len(freq)
            n = len(freq[0])

            cnt = 0
            for i in range(m):
                for j in range(n):
                    if freq[i,j]:
                        q.put((freq[i,j], str((i,j))))
                        cnt += 1

            for i in range(cnt-1):
                a = q.get()
                b = q.get()
                q.put((a[0]+b[0], str("[" + a[1] + "," + b[1] + "]")))

            tree = eval(q.get()[1])
            return tree

        tree = make_tree(freq)
        code_lengths = np.zeros(freq.shape, dtype=int)

        depth = 0
        def get_depths(arr, code_lengths):
            global depth
            if type(arr[1]) == int and type(arr[0]) == int:
                code_lengths[arr[0], arr[1]] = min(depth, 16)
            else:
                depth += 1
                get_depths(arr[0], code_lengths)
                get_depths(arr[1], code_lengths)
                depth-=1

        get_depths(tree, code_lengths)
        return code_lengths
    
    code_lengths = get_code_lengths_from_huf(hufs[index], freq.shape[0], freq.shape[1])
    code_lengths = get_code_lengths(freq)
    
    length_symbol_pairs = []
    
    m, n = freq.shape
    for i in range(m):
        for j in range(n):
            if code_lengths[i, j]:
                length_symbol_pairs.append((code_lengths[i, j], (i, j)))
    length_symbol_pairs.sort()
    
    def get_code(code, length):
        st = bin(code).replace("0b", "")[::-1]
        while len(st) < length:
            st += '0'
        return st[::-1]
    
    code = 0
    cur_len = 0
    last = length_symbol_pairs[-1]
    length_symbol_pairs[-1] = (last[0] + 1, last[1])
    for length, symbol in length_symbol_pairs:
        while cur_len < length:  #if there is no symbol with the current length
            cur_len += 1
            code *= 2
        codebook[symbol[0], symbol[1]] = get_code(code, length)
        code += 1
    
#     print(length_symbol_pairs)
    return codebook, length_symbol_pairs

codes_dc_Y, sorted_symbols_dc_Y = get_codebook(dc_huffman_Y, 0)
codes_ac_Y, sorted_symbols_ac_Y = get_codebook(ac_huffman_Y, 1)
codes_dc_C, sorted_symbols_dc_C = get_codebook(dc_huffman_C, 2)
codes_ac_C, sorted_symbols_ac_C = get_codebook(ac_huffman_C, 3)
# print(list(codes_dc_Y))
# print(codes_ac_Y[15, 0])

def to_two_bytes(num):
    bh = bin(num).replace("0b", "")
    bh = bh[::-1]
    while len(bh) < 16:
        bh += '0'
    bh = bh[::-1]

    result = [int(bh[:8], 2), int(bh[8:], 2)]
    print(num, result)
    return result

# Writing jpeg image in binary
jpeg_image = [0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10]

header = [0x4a, 0x46, 0x49, 0x46, 0x00, 0x01, 0x01, 0x01, 0x00, 0x48, 0x00, 0x48, 0x00, 0x00]
jpeg_image.extend(header)

luminance_quantisation_table = [0xff, 0xdb, 0x00, 0x43, 0x00]
luminance_quantisation_table.extend([int(ele) for ele in spiral_traversal(Y_q)])
jpeg_image.extend(luminance_quantisation_table)

chrominance_quantisation_table = [0xff, 0xdb, 0x00, 0x43, 0x01]
chrominance_quantisation_table.extend([int(ele) for ele in spiral_traversal(C_q)])
jpeg_image.extend(chrominance_quantisation_table)

start_of_frame = [0xff, 0xc0, 0x00, 0x11, 0x08]
start_of_frame.extend(to_two_bytes(old_shape[0]))
start_of_frame.extend(to_two_bytes(old_shape[1]))
start_of_frame.extend([0x03, 0x01, 0x22, 0x00, 0x02, 0x11, 0x01, 0x03, 0x11, 0x01])
jpeg_image.extend(start_of_frame)

def parse_table(sorted_symbols, typ):
    table = [0xff, 0xc4]
    ln = 19
    symbols = []
    freqs = [0 for i in range(16)]
    
    for length, symbol in sorted_symbols:
#         print(length)
        freqs[length-1] += 1
        symbols.append(symbol[0] * 16 + symbol[1])
        ln += 1
#     print()
    
    table.extend(to_two_bytes(ln))
    table.append(typ)
    table.extend(freqs)
    table.extend(symbols)
    return table

jpeg_image.extend(parse_table(sorted_symbols_dc_Y, 0x00))
jpeg_image.extend(parse_table(sorted_symbols_ac_Y, 0x10))
jpeg_image.extend(parse_table(sorted_symbols_dc_C, 0x01))
jpeg_image.extend(parse_table(sorted_symbols_ac_C, 0x11))

start_of_scan = [0xff, 0xda, 0x00, 0x0c, 0x03, 0x01, 0x00, 0x02, 0x11, 0x03, 0x11, 0x00, 0x3f, 0x00]
jpeg_image.extend(start_of_scan)

def bit_rep(value):
    if value == 0:
        return ''
    else : 
        v = bin(abs(value)).replace("0b", '')
        if value>0 :
            return v
        else:
            return v.replace('0', 'a').replace('1','0').replace('a','1')

def encode_data(encoded_Y, encoded_Cb, encoded_Cr, codes_dc_Y, code_dc_C, codes_ac_Y, codes_ac_C):
    s = ''
    def encode_block(block, dc_codebook, ac_codebook):
        print(block)
        ans = ''
        dc_val = block[0][1]
        cat = get_cat(dc_val)
        print(dc_codebook[0,cat]+bit_rep(dc_val))
        ans+=(dc_codebook[0,cat]+bit_rep(dc_val))
        
        for i in range(1, len(block)):
            run, val = block[i]
#             print(run, get_cat(val))
            print(ac_codebook[run, get_cat(val)]+bit_rep(val))
            ans+=(ac_codebook[run, get_cat(val)]+bit_rep(val))
        return ans
    
    for i in range(len(encoded_Y)):
        print(i)
        s += encode_block(encoded_Y[i], codes_dc_Y, codes_ac_Y)
        if (i% 4 == 3):
            print('cbcr')
            s += encode_block(encoded_Cb[(i) // 4], codes_dc_C, codes_ac_C)
            s += encode_block(encoded_Cr[(i) // 4], codes_dc_C, codes_ac_C)
        
    #pad with 0s
    a = len(s)%8
    s+='0'*a
    
    data = [int(s[i:i+8], 2) for i in range(0, len(s), 8)]
    fin_data = []
    for ele in data:
        fin_data.append(ele)
        if ele == 0xff:
            fin_data.append(0x00)
    return fin_data

jpeg_image.extend(encode_data(encoded_Y, encoded_Cb, encoded_Cr, codes_dc_Y, codes_dc_C, codes_ac_Y, codes_ac_C))

end_of_image = [0xff, 0xd9]
jpeg_image.extend(end_of_image)

try:
    with open("my_image.jpeg", 'wb') as f:
        for byte in jpeg_image:
            f.write(byte.to_bytes(1, byteorder='big'))
except Exception as e:
    print(e)

file = open('my_image.jpeg', 'rb')
data = file.read()
s = data.hex()

l = re.findall('..?', s)
while len(l) % 11:
    l = np.append(l, '0')
d = np.reshape(l, (-1,11))
d = [' '.join(ele) for ele in d]
print(len(d))
for ele in d:
    print(ele)

file.close()

256 [1, 0]
256 [1, 0]
29 [0, 29]
66 [0, 66]
28 [0, 28]
58 [0, 58]
0
[[  0 339]
 [  0   0]]
1111110101010011
1010
1
[[0 0]
 [0 0]]
0
1010
2
[[0 0]
 [0 0]]
0
1010
3
[[0 0]
 [0 0]]
0
1010
cbcr
[[0 0]
 [0 0]]
0
010
[[0 0]
 [0 0]]
0
010
4
[[0 0]
 [0 0]]
0
1010
5
[[0 0]
 [0 0]]
0
1010
6
[[0 0]
 [0 0]]
0
1010
7
[[0 0]
 [0 0]]
0
1010
cbcr
[[0 0]
 [0 0]]
0
010
[[0 0]
 [0 0]]
0
010
8
[[0 0]
 [0 0]]
0
1010
9
[[0 0]
 [0 0]]
0
1010
10
[[0 0]
 [0 0]]
0
1010
11
[[0 0]
 [0 0]]
0
1010
cbcr
[[0 0]
 [0 0]]
0
010
[[0 0]
 [0 0]]
0
010
12
[[0 0]
 [0 0]]
0
1010
13
[[0 0]
 [0 0]]
0
1010
14
[[0 0]
 [0 0]]
0
1010
15
[[0 0]
 [0 0]]
0
1010
cbcr
[[0 0]
 [0 0]]
0
010
[[0 0]
 [0 0]]
0
010
16
[[0 0]
 [0 0]]
0
1010
17
[[0 0]
 [0 0]]
0
1010
18
[[0 0]
 [0 0]]
0
1010
19
[[0 0]
 [0 0]]
0
1010
cbcr
[[0 0]
 [0 0]]
0
010
[[0 0]
 [0 0]]
0
010
20
[[0 0]
 [0 0]]
0
1010
21
[[0 0]
 [0 0]]
0
1010
22
[[0 0]
 [0 0]]
0
1010
23
[[0 0]
 [0 0]]
0
1010
cbcr
[[0 0]
 [0 0]]
0
010
[[0 0]
 [0 0]]
0
010
24
[[0 0]
 [0 0]]
0
1010
25
[[0 0]
 [0 

1010
975
[[0 0]
 [0 0]]
0
1010
cbcr
[[0 0]
 [0 0]]
0
010
[[0 0]
 [0 0]]
0
010
976
[[0 0]
 [0 0]]
0
1010
977
[[0 0]
 [0 0]]
0
1010
978
[[0 0]
 [0 0]]
0
1010
979
[[0 0]
 [0 0]]
0
1010
cbcr
[[0 0]
 [0 0]]
0
010
[[0 0]
 [0 0]]
0
010
980
[[0 0]
 [0 0]]
0
1010
981
[[0 0]
 [0 0]]
0
1010
982
[[0 0]
 [0 0]]
0
1010
983
[[0 0]
 [0 0]]
0
1010
cbcr
[[0 0]
 [0 0]]
0
010
[[0 0]
 [0 0]]
0
010
984
[[0 0]
 [0 0]]
0
1010
985
[[0 0]
 [0 0]]
0
1010
986
[[0 0]
 [0 0]]
0
1010
987
[[0 0]
 [0 0]]
0
1010
cbcr
[[0 0]
 [0 0]]
0
010
[[0 0]
 [0 0]]
0
010
988
[[0 0]
 [0 0]]
0
1010
989
[[0 0]
 [0 0]]
0
1010
990
[[0 0]
 [0 0]]
0
1010
991
[[0 0]
 [0 0]]
0
1010
cbcr
[[0 0]
 [0 0]]
0
010
[[0 0]
 [0 0]]
0
010
992
[[0 0]
 [0 0]]
0
1010
993
[[0 0]
 [0 0]]
0
1010
994
[[0 0]
 [0 0]]
0
1010
995
[[0 0]
 [0 0]]
0
1010
cbcr
[[0 0]
 [0 0]]
0
010
[[0 0]
 [0 0]]
0
010
996
[[0 0]
 [0 0]]
0
1010
997
[[0 0]
 [0 0]]
0
1010
998
[[0 0]
 [0 0]]
0
1010
999
[[0 0]
 [0 0]]
0
1010
cbcr
[[0 0]
 [0 0]]
0
010
[[0 0]
 [0 0]]
0
010
1000
[[0 0]
 [0 

In [48]:
image = Image.open('my_image.jpeg')
image.thumbnail((256, 256))
image = image.convert("RGB")
image = np.asarray(image, dtype=np.float32) / 256

new_image = np.zeros(image.shape, dtype = np.float32)
new_image[:,:,0] = image[:,:,2]
new_image[:,:,1] = image[:,:,1]
new_image[:,:,2] = image[:,:,0]

new_image = cv2.imread('my_image.jpeg')
imgYCC = cv2.cvtColor(new_image, cv2.COLOR_BGR2YCR_CB)
cv2.imshow('hello', imgYCC[:,:,0])
cv2.waitKey(0)
cv2.destroyAllWindows()